# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - inteliBudgetOrchestrator

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: hackutd-project-2025 # Set to the subfolder containing your app
  NODE_VERSION: '22.x' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest # Switched to ubuntu-latest as recommended for speed
    permissions:
      contents: read #This is required for actions/checkout
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: 'Resolve Project Dependencies Using pnpm'
        shell: bash
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} # Run commands inside the subfolder
        run: |
          pnpm install
          pnpm run build --if-present
          pnpm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.output # Upload the build output

  deploy:
    runs-on: ubuntu-latest # Switched to ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'inteliBudgetOrchestrator'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2A864BA503C141C7AD99151202CFDCED }}